# =============================================
# ms-transferencias - Puerto 8090
# =============================================
server.port=8090
spring.application.name=ms-transferencias

spring.datasource.url=jdbc:mysql://localhost:3306/db_transferencias?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# URLs de microservicios externos
microservicios.ms-jugadores.url=http://localhost:8081/api/v1/jugadores
microservicios.ms-equipos.url=http://localhost:8082/api/v1/equipos

logging.level.com.esports.mstransferencias=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
