server.port=8086
spring.application.name=ms-estadisticas

spring.datasource.url=jdbc:mysql://localhost:3306/ms_estadisticas?createDatabaseIfNotExist=true&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true

microservicios.ms-jugadores.url=http://localhost:8081/api/v1/jugadores
microservicios.ms-partidas.url=http://localhost:8085/api/v1/partidas

logging.level.com.esports.msestadisticas=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n